**IMPORTING LIBRARIES**

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

%matplotlib inline

**LOAD & CLEAN DATA**

In [2]:
df = pd.read_excel("Mosoriot Data.xlsx")

df.columns = df.columns.str.strip()
df.drop('Serial No', axis=1, inplace=True)
df.head()

,Age,Sex,Marital Status,Level of Education,Have you heard about SHA?,Where did you hear about SHA,Do you know how someone can register for SHA?,"In your opinion, how sufficient is the knowledge you have about SHA?",Are you currently registered under SHA?,How long have you been enrolled?,...,Has SHA helped reduce the amount of money you personally spend on healthcare?,Are there healtcare services you stilll have to pay for after enrolling in SHA?,Have you experienced any difficulties when trying to access healthcare services through SHA?,Do you think the registration process for SHA is easy ordifficult?,SHA has improved my ability to receive medical care,Medicines are usually available when I visit the facility,The services covered by SHA meet my healthcare needs,SHA has reduced my personal spending on SHA,I feel financially protected when seeking treatment under SHA,Would you recommend SHA to older adults?
0,70,1,1,4,1,4,1,5,1,2,...,1,1,5,2,4,2,5,5,5,1
1,80,1,1,4,1,3,1,4,1,1,...,1,2,5,2,5,5,5,5,5,1
2,68,2,2,2,1,4,2,2,1,1,...,1,2,5,2,5,5,5,5,5,1
3,62,1,1,2,1,"1,2",1,5,1,2,...,1,2,5,3,3,3,3,5,5,1
4,62,2,2,2,1,1,2,2,1,2,...,1,1,5,2,5,3,5,5,5,1

**Basic exploration**

In [3]:
df.shape

(45, 22)

In [4]:
df.columns

Index(['Age', 'Sex', 'Marital Status', 'Level of Education',
       'Have you heard about SHA?', 'Where did you hear about SHA',
       'Do you know how someone can register for SHA?',
       'In your opinion, how sufficient is the knowledge you have about SHA?',
       'Are you currently registered under SHA?',
       'How long have you been enrolled?',
       'How often do you visit a health facility now compared to before enrolling?',
       'What types of health services have you accessed through SHA?',
       'Has SHA helped reduce the amount of money you personally spend on healthcare?',
       'Are there healtcare services you stilll have to pay for after enrolling in SHA?',
       'Have you experienced any difficulties when trying to access healthcare services through SHA?',
       'Do you think the registration process for SHA is easy ordifficult?',
       'SHA has improved my ability to receive medical care',
       'Medicines are usually available when I visit the facility',
       'The services covered by SHA meet my healthcare needs',
       'SHA has reduced my personal spending on SHA',
       'I feel financially protected when seeking treatment under SHA',
       'Would you recommend SHA to older adults?'],
      dtype='str')

**MAPPING OF CATEGORICAL VARIABLES**

In [5]:
yesNo = {
    0: 'No response',
    1: 'Yes',
    2: 'No',
    3: 'Not Sure',
}

sex = {
    0: 'No response',
    1: 'Male',
    2: 'Female'
}

maritalStatus = {
    0: 'No response',
    1: 'Married',
    2: 'Widowed',
    3: 'Single',
    4: 'Divorced/Separated',
}
education = {
    0: 'No response',
    1: 'No formal education',
    2: 'Primary',
    3: 'Secondary',
    4: 'Tertiary',
    5: 'Other',
}
sufficiency = {
    0: 'No response',
    1: 'Very insufficienct',
    2: 'Insufficient',
    3: 'Neutral',
    4: 'Sufficient',
    5: 'Very Sufficient'
}

enrollmentTime = {
    0: 'No response',
    1: 'Less than 1 year',
    2: '1-2 years',
    3: 'Not Sure'
}

visits = {
    0: 'No response',
    1: 'More Often',
    2: 'Less Often',
    3: 'The Same',
}

ease = {
    0: 'No response',
    1: 'Very easy',
    2: 'Easy',
    3: 'Neutral',
    4: 'Hard',
    5: 'Very Hard'
}

agreement = {
    0: 'No response',
    1: 'Strongly Disagree',
    2: 'Disagree',
    3: 'Neutral',
    4: 'Agree',
    5: 'Strongly Agree',
}

# Apply Mappings

df['Sex'] = df['Sex'].map(sex)
df['Marital Status'] = df['Marital Status'].map(maritalStatus)
df['Level of Education'] = df['Level of Education'].map(education)

df['Have you heard about SHA?'] = df['Have you heard about SHA?'].map(yesNo)
df['Do you know how someone can register for SHA?'] = df['Do you know how someone can register for SHA?'].map(yesNo)
df['Are you currently registered under SHA?'] = df['Are you currently registered under SHA?'].map(yesNo)

df['In your opinion, how sufficient is the knowledge you have about SHA?'] = df['In your opinion, how sufficient is the knowledge you have about SHA?'].map(sufficiency)
df['How long have you been enrolled?'] = df['How long have you been enrolled?'].map(enrollmentTime)
df['How often do you visit a health facility now compared to before enrolling?'] = df['How often do you visit a health facility now compared to before enrolling?'].map(visits)

df['Has SHA helped reduce the amount of money you personally spend on healthcare?'] = df['Has SHA helped reduce the amount of money you personally spend on healthcare?'].map(yesNo)
df['Are there healtcare services you stilll have to pay for after enrolling in SHA?'] = df['Are there healtcare services you stilll have to pay for after enrolling in SHA?'].map(yesNo)

df['Do you think the registration process for SHA is easy ordifficult?'] = df['Do you think the registration process for SHA is easy ordifficult?'].map(ease)

# Likert scale columns
likert_cols = [
    'SHA has improved my ability to receive medical care',
    'Medicines are usually available when I visit the facility',
    'The services covered by SHA meet my healthcare needs',
    'SHA has reduced my personal spending on SHA',
    'I feel financially protected when seeking treatment under SHA'
]

for c in likert_cols: 
    df[c] = df[c].map(agreement)

df['Would you recommend SHA to older adults?'] = df['Would you recommend SHA to older adults?'].map(yesNo)
df.head()

,Age,Sex,Marital Status,Level of Education,Have you heard about SHA?,Where did you hear about SHA,Do you know how someone can register for SHA?,"In your opinion, how sufficient is the knowledge you have about SHA?",Are you currently registered under SHA?,How long have you been enrolled?,...,Has SHA helped reduce the amount of money you personally spend on healthcare?,Are there healtcare services you stilll have to pay for after enrolling in SHA?,Have you experienced any difficulties when trying to access healthcare services through SHA?,Do you think the registration process for SHA is easy ordifficult?,SHA has improved my ability to receive medical care,Medicines are usually available when I visit the facility,The services covered by SHA meet my healthcare needs,SHA has reduced my personal spending on SHA,I feel financially protected when seeking treatment under SHA,Would you recommend SHA to older adults?
0,70,Male,Married,Tertiary,Yes,4,Yes,Very Sufficient,Yes,1-2 years,...,Yes,Yes,5,Easy,Agree,Disagree,Strongly Agree,Strongly Agree,Strongly Agree,Yes
1,80,Male,Married,Tertiary,Yes,3,Yes,Sufficient,Yes,Less than 1 year,...,Yes,No,5,Easy,Strongly Agree,Strongly Agree,Strongly Agree,Strongly Agree,Strongly Agree,Yes
2,68,Female,Widowed,Primary,Yes,4,No,Insufficient,Yes,Less than 1 year,...,Yes,No,5,Easy,Strongly Agree,Strongly Agree,Strongly Agree,Strongly Agree,Strongly Agree,Yes
3,62,Male,Married,Primary,Yes,"1,2",Yes,Very Sufficient,Yes,1-2 years,...,Yes,No,5,Neutral,Neutral,Neutral,Neutral,Strongly Agree,Strongly Agree,Yes
4,62,Female,Widowed,Primary,Yes,1,No,Insufficient,Yes,1-2 years,...,Yes,Yes,5,Easy,Strongly Agree,Neutral,Strongly Agree,Strongly Agree,Strongly Agree,Yes

**CREATE A CLEAN MAIN DATASET**

In [6]:
df_main = df.copy()

**CLEAN AND EXPLODE**

In [7]:
# Function to clean & explode
def explode_column (dataframe, column_name):
    df_temp = dataframe.copy()

    df_temp[column_name] = df_temp[column_name].astype(str).str.replace(" ", "")
    df_temp[column_name] = df_temp[column_name].replace("nan", pd.NA)
    df_temp[column_name] = df[column_name].dropna().apply(lambda x: str(x).split(','))

    df_temp = df_temp.explode(column_name)
    df_temp = df_temp.dropna(subset=[column_name])

    df_temp[column_name] = df_temp[column_name].astype(int)

    return df_temp

# Creating exploded data sets
# 1. Sources of Information
df_sources = explode_column(df_main, 'Where did you hear about SHA')
sources = {
    0: 'No Response',
    1: 'Radio',
    2: 'Television',
    3: 'Community Meetings',
    4: 'Health Workers',
    5: 'Family/Friends',
    6: 'Mobile Phone',
    7: 'Social Media',
    8: 'Other',
}
df_sources['Where did you hear about SHA'] = df_sources['Where did you hear about SHA'].map(sources)

# 2. Services accessed
df_services = explode_column(df_main, 'What types of health services have you accessed through SHA?')
services = {
    0: 'No response',
    1: 'Outpatient Services',
    2: 'Inpatient Services',
    3: 'Medications',
    4: 'Laboratory Tests',
    5: 'Other', 
}
df_services['What types of health services have you accessed through SHA?'] = df_services['What types of health services have you accessed through SHA?'].map(services)

# 3. Difficulties
df_difficulties = explode_column(df_main, 'Have you experienced any difficulties when trying to access healthcare services through SHA?')
difficulties = {
    0: 'No Response',
    1: 'Lack of information',
    2: 'Difficulty registering',
    3: 'Technological difficulties',
    4: 'Transport Cost',
    5: 'Other'
}
df_difficulties['Have you experienced any difficulties when trying to access healthcare services through SHA?'] = df_difficulties['Have you experienced any difficulties when trying to access healthcare services through SHA?'].map(difficulties)

**Basic Analysis**

**Demographics**

*Age Summary*

In [8]:
print(df_main['Age'].describe())

count    45.000000
mean     68.866667
std       8.089275
min      60.000000
25%      62.000000
50%      68.000000
75%      73.000000
max      89.000000
Name: Age, dtype: float64

*Sex Distribution*

In [9]:
print(df_main['Sex'].value_counts())

Sex
Female    23
Male      22
Name: count, dtype: int64

*Marriage Status*

In [10]:
print(df_main['Marital Status'].value_counts())

Marital Status
Married    31
Widowed    14
Name: count, dtype: int64

*Level of Education*

In [11]:
print(df_main['Level of Education'].value_counts())

Level of Education
Primary                24
Secondary              11
No formal education     6
Tertiary                3
Other                   1
Name: count, dtype: int64

**Awareness of SHA**

*Heard about SHA*

In [12]:
print(df_main['Have you heard about SHA?'].value_counts())

Have you heard about SHA?
Yes    45
Name: count, dtype: int64

*Sources of information*

In [13]:

print(df_sources['Where did you hear about SHA'].value_counts())

Where did you hear about SHA
Health Workers        17
Radio                 17
Television            13
Community Meetings     8
Family/Friends         8
Mobile Phone           2
Social Media           1
No Response            1
Name: count, dtype: int64

*Know how to register*

In [14]:
print(df_main['Do you know how someone can register for SHA?'].value_counts())

Do you know how someone can register for SHA?
Yes    24
No     21
Name: count, dtype: int64

Sufficiency of Knowledge

In [15]:
print(df_main['In your opinion, how sufficient is the knowledge you have about SHA?'].value_counts())

In your opinion, how sufficient is the knowledge you have about SHA?
Insufficient          14
Sufficient            13
Neutral                8
Very Sufficient        5
Very insufficienct     4
No response            1
Name: count, dtype: int64

**Perceived Impact of SHA**

*Enrollment Status*

In [16]:
print(df_main['Are you currently registered under SHA?'].value_counts())

Are you currently registered under SHA?
Yes    40
No      5
Name: count, dtype: int64

*Length of enrollment*

In [17]:
print(df_main['How long have you been enrolled?'].value_counts())

How long have you been enrolled?
1-2 years           29
Less than 1 year     8
No response          5
Not Sure             3
Name: count, dtype: int64

*How often do you visit a health facility compared to before enrolling for SHA*

In [18]:
print(df_main['How often do you visit a health facility now compared to before enrolling?'].value_counts())

How often do you visit a health facility now compared to before enrolling?
The Same       23
More Often     16
No response     5
Less Often      1
Name: count, dtype: int64

*Types of services accessed*

In [19]:
print(df_services['What types of health services have you accessed through SHA?'].value_counts())

What types of health services have you accessed through SHA?
Outpatient Services    34
Medications            30
Laboratory Tests       25
Inpatient Services     11
No response             6
Other                   5
Name: count, dtype: int64

*Reduced Spending*

In [20]:
print(df_main['Has SHA helped reduce the amount of money you personally spend on healthcare?'].value_counts())

Has SHA helped reduce the amount of money you personally spend on healthcare?
Yes            32
No              8
No response     5
Name: count, dtype: int64

**Barriers to Utilization**

*Difficulties experienced*

In [21]:
print(df_difficulties['Have you experienced any difficulties when trying to access healthcare services through SHA?'].value_counts());

Have you experienced any difficulties when trying to access healthcare services through SHA?
Other                         29
Lack of information            8
Technological difficulties     5
Transport Cost                 3
Difficulty registering         3
No Response                    2
Name: count, dtype: int64

*Ease of registration*

In [22]:
print(df_main['Do you think the registration process for SHA is easy ordifficult?'].value_counts())

Do you think the registration process for SHA is easy ordifficult?
Easy           17
Very easy      17
Neutral         5
Hard            5
No response     1
Name: count, dtype: int64

**Satisfaction with SHA Services**

*SHA has improved my ability to receive medical care*

In [23]:
print(df_main['SHA has improved my ability to receive medical care'].value_counts())

SHA has improved my ability to receive medical care
Strongly Agree    20
Agree             14
Neutral            6
No response        4
Disagree           1
Name: count, dtype: int64

*Medicines are usually available when I visit the facility*

In [24]:
print(df_main['Medicines are usually available when I visit the facility'].value_counts())

Medicines are usually available when I visit the facility
Neutral              14
Strongly Agree       11
Disagree             10
Agree                 4
No response           4
Strongly Disagree     2
Name: count, dtype: int64

*The services covered by SHA meet my healthcare needs*

In [25]:
print(df_main['The services covered by SHA meet my healthcare needs'].value_counts())

The services covered by SHA meet my healthcare needs
Strongly Agree       21
Agree                 9
Neutral               8
No response           4
Disagree              2
Strongly Disagree     1
Name: count, dtype: int64

*SHA has reduced my personal spending on SHA*

In [26]:
print(df_main['SHA has reduced my personal spending on SHA'].value_counts())

SHA has reduced my personal spending on SHA
Strongly Agree       21
Agree                11
Neutral               7
No response           4
Strongly Disagree     2
Name: count, dtype: int64

*I feel financially protected when seeking treatment under SHA*

In [27]:
print(df_main['I feel financially protected when seeking treatment under SHA'].value_counts())

I feel financially protected when seeking treatment under SHA
Strongly Agree       19
Agree                13
Neutral               6
No response           4
Strongly Disagree     2
Disagree              1
Name: count, dtype: int64

*Would you recommend SHA to older adults*

In [28]:
print(df_main['Would you recommend SHA to older adults?'].value_counts())

Would you recommend SHA to older adults?
Yes         41
Not Sure     3
No           1
Name: count, dtype: int64